server:
  port: 8765
  
ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 990000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true  
  
zuul:
  ignoredServices: '*'
  routes:
    post:
      path: /post/**
      stripPrefix: false
      serviceId: post
      sensitiveHeaders:
    teste:
      path: /teste/**
      stripPrefix: false
      serviceId: teste
      #url: http://localhost:8081/
      sensitiveHeaders:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
spring:      
  boot:
    admin:
      url: http://localhost:7070
      #username: admin
      #password: admin123
management:
  security:
    enabled: false            