server:
  port: 8761
security:
  user:
    password: ${eureka.password} # Don't use a default password in a real app
info:
  component: Eureka Server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  password: ${SECURITY_USER_PASSWORD:password}

spring:
  boot:
    admin:
      url: http://localhost:7070
      #username: admin
      #password: admin123
management:
  security:
    enabled: false        